spring.application.name=vorstu
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driverClassname=org.postgresql.Driver
##PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=dearDatabase!
spring.jpa.hibernate.ddl-auto=create

